subway:
	wget -np -r -I '/life/access/transport/subway/img/' http://www.city.kobe.lg.jp/life/access/transport/subway/opendeta.html
	git add www.city.kobe.lg.jp/life/access/transport/subway/img/*.csv

